# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cozy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cozy
  pod 'Alamofire', '~> 4.8.2'
  pod 'Kingfisher', '~> 5.0'
  pod 'Cosmos', '~> 22.1'

end
